---
title: "Write Up"
author: "C.Fogler"
format: html
editor: visual
---

## Introduction

In this decade, we have seen major advancements in the use of analytics in sports. Whether it is used from a business prospective, player development prospective, or game play prospective, there are so many cool ways to use analytics to improve your team. In football, one of the greatest uses of analytics is finding tendencies in a teams playing schemes, measuring their efficiency, and finding a way to get the upper edge off the field. As a kicker on a small division 3 football school, the use if analytics is very minimal as stat keeping is kept on a basic level. However, just because very little data is recorded, doesn't mean we can't find ways to use the data to improve our success.

The goal for my Senior Year Experience is to evaluate my teams' offensive success rates using both exploratory statistics and Bayesian analysis to improve our offensive efficiency. By studying the play by play data from both past seasons and our current one, I will be able to find patterns in both our play calling tendencies, our efficiency in specific situations. and potentially develop a program that simulates our drives. Later in the paper, we will define what we call a successful play and go into details about our methods.

This research will directly help the team as identifying our tendencies and efficiencies will tell us our strengths and weaknesses, improving our play designs, playbook, and player development. By using Bayesian methods, along with exploratory statistics, we will be able to build models that can be updated as the season moves on to see if our changes are working. This will help our coaching staff handle uncertainties when trying to game plan for the game.

My project will begin with basic exploratory data analysis based off last years games to get an understanding for the offense and find early trends. Things we will look at include success rates based on formation, play type, situation, and more. We will then use these findings to build some logistic regression models before building our priors for our Bayesian analysis. Finally, we will use data from this years games to update our beliefs and find ways to improve our offensive efficiency.

## Explanatory Tables and Descriptions

Before we can go into the research, we must first understand how we are gathering our data. Like most teams in division 3 football, we use a software called Hudl. It is a subscription-based website in which teams can upload film from games and practices and input data such as down, distance, personnel, and more. After recording our plays and updating them to hudl, the coaching staff goes through the film to write down the stats for each play.

*maybe add a screen shot or two of hudl here to show what it looks like, what the data looks like on hudl*

After downloading the data from hudl as an excel file, all I do is convert it into a csv and load the file into r studio.

After getting the data into r studio,

link for success rates: https://www.footballstudyhall.com/2012/2/16/2798555/in-defense-of-success-rates?utm_source=chatgpt.com

Different Kinds of Personnel used in our dataset:

10, 11, 12, 20, 21, 22, ALPHA, BEEF, JET, PIG, PORK, and VICTORY

With numbered personnel's, the two numbers are used to tell the offense how many tight ends and running backs will be on the field. After factoring 5 offensive lineman and 1 quarterback, this means their are 5 remaining players allowed on the field. The first digit refers to the number of Tight Ends on the field. The second digit refers to the number of running backs on the field. Finally, if those two digits do not add to 5, the remaining number of players are wide receivers.

For example, 12 personnel means their is 1 tight end, 2 running backs, and 2 wide receivers on the field. 11 personnel means their is 1 tight end, 1 running back, and 3 wide receivers on the field.

With named personnel's, this usually refers to a specific game plan package that is unique to certain players. Maybe talk to puck about what exactly is in ALPHA, BEEF, JET, PIG, PORK, and VICTORY.

------------------------------------------------------------------------

Outline For How I Want to Set My Paper Up:

*Introduction* - Introduce project - have a section dedicated to explaining just the football terminology used - Introduce the idea that we are going to use 4 different methods to see which is best for trying to predict success in offense

*Data Gathering* - Explained how I gathered my data - Explain hudl - how i transfered it from google sheets into a csv file
- explain all of the different formations
- explain how i tidy the data to make it easier to work with

*Exploratory Research* - introduce our first steps in exploring the data - use the exploratory plots that Ive created to continue introducing our data

*Method 1: Logistic Regression Models*
- Started off by making 4 models with just one predictor to see which predictor was the strongest (dist)
- Then made a model with all 4 of my predictors in it and used step wise to narrow down the best model which ended up being DIST, DN, and RP
- Put the model through a 5 fold cross validation, then found the classifcation rate: 
- insert graph of predicted values


*Method 2: Interaction Testing*
- Made a model with all 4 of my predictors in it along with interactiont term for all of them
- Used step wise to narrow down the best model which ended up being:
- Put the model through a 5 fold cross validation, then found the classifcation rate: 
- insert graph of predicted values

*Method 3: Classification Trees*
- what are classification trees
- how classification trees are helpful
- Created a classification tree
- classification rate: 

*Method 4: Bagging / Random Forest*
- what is bagging
- how is bagging helpful
- Created a bagging model
- classification rate: 

repeat the process for random forest

*Compare and Contrast the 4 methods*
-Using the classification rates, paste all classifcation rates and compare them
- which is the best model? Which was the worst?
- What makes the model the best model or worst model. 




*Conclusion*

End with any sources i may have used throughout my work
